name: proscholy_common
description: "A collection of common sources for proscholy-like songbooks."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.0
  dotted_border: ^3.1.0
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.0.0
  intl: any
  json_annotation: ^4.9.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  riverpod_annotation: ^3.0.0
  sentry_flutter: ^9.6.0
  shared_preferences: ^2.4.0
  sqflite: ^2.4.1
  package_info_plus: ^9.0.0
  flutter_quill: ^11.0.0
  adaptive_dialog: ^2.4.0
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  graphql_flutter: ^5.2.0-beta.8
  just_audio: ^0.10.2
  rxdart: ^0.28.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  wakelock_plus: ^1.2.10
  flutter_speed_dial: ^7.0.0
  flex_color_picker: ^3.7.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_cached_pdfview: ^0.4.3
  youtube_player_flutter: ^9.1.1
  jovial_svg: ^1.1.24
  archive: ^4.0.2
  http: ^1.3.0
  firebase_analytics: ^11.6.0
  url_launcher: ^6.3.2
  sqlite_bm25: ^0.3.0
  path: ^1.9.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: any
  freezed: any
  json_serializable: any
  objectbox_generator: any
  riverpod_generator: any
  mocktail: any

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: cz.glowspace.proscholy_common
        pluginClass: ProscholyCommonPlugin
      ios:
        pluginClass: ProscholyCommonPlugin

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/songbooks/
    - assets/

objectbox:
  output_dir: models/generated
